### ISSUE TITLE
[pywebview] WebView2 initialization failed with exception --2

### ISSUE THREAD

**Issue by GGTEC** [r0x0r/pywebview#1026]
### Specification
- pywebview version: 4.0.1
- operating system: Windows 11
- web renderer:  EDGE 44.22621.1105.0

### Description  
  
  Just run that 
  
  ```
  import webview

  window = webview.create_window("test", "https://www.google.com/", width=1200, height=680, min_size=(1200, 680))
  webview.start()
  ```
  
  And console show that 
  
  ```
  [pywebview] WebView2 initialization failed with exception:
 Acesso negado. (Exceção de HRESULT: 0x80070005 (E_ACCESSDENIED))
   em System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   em Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__25.MoveNext()
 ```

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
This might help https://github.com/MicrosoftEdge/WebView2Feedback/issues/1893

**Comment by GGTEC** [comment]
Hello, sorry for the delay in responding.

I read the possible solution, but I didn't quite understand what to do with it. where is to create the folder with the bin if I'm running a .py , and this launch.json is exactly where?

**Comment by r0x0r** [comment]
Check this issue
https://github.com/r0x0r/pywebview/issues/1037

**Comment by GGTEC** [comment]
Fixed, with 'private_mode' set to false and specifying 'storage_path'

**Comment by nadaa** [comment]
Hi, I have the same issue, I tried to set private_mode=False but the error is still there, any suggestion? Thanks
