### ISSUE TITLE
pyinstaller After compilation erro

### ISSUE THREAD

**Issue by zd20041** [r0x0r/pywebview#1029]
### Specification
- pywebview version: 4.0.1
- operating system:  win11 20h2
- web renderer: I don't know

### Description  
 code 
import webview
webview.create_window('Hello world', 'https://pywebview.flowrl.com/')
webview.start()

error 
Traceback (most recent call last):
  File "test1.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "webview\__init__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "webview\http.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "bottle.py", line 73, in <module>
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by zd20041** [comment]
compile cmd : pyinstaller -F -w main.py

**Comment by simonrob** [comment]
The same issue has been [reported](https://github.com/simonrob/email-oauth2-proxy/issues/134) on a project of mine. I believe it is related to [this change](https://github.com/pyinstaller/pyinstaller/issues/3503) in PyInstaller 5.7.0 which now handles `stdout` and `stderr` in the same way as `pythonw` would (i.e., they are `None`). The exception actually happens with `bottle`, but the [previous discussion](https://github.com/bottlepy/bottle/issues/1401) of this sort of thing over there suggests it is down to the end user (i.e., pywebview) to handle this, rather than that package.

Replicate by compiling the pywebview hello world example with `pyinstaller --noconsole --onefile demo.py`.

**Comment by r0x0r** [comment]
I have implemented a fix based on one of linked discussions in the https://github.com/r0x0r/pywebview/tree/logwriter-bottle branch. Please test.

**Comment by zd20041** [comment]
> 我已经根据 https://github.com/r0x0r/pywebview/tree/logwriter-bottle 分支中的链接讨论之一实施了修复程序。请测试。
This version is no problem, thanks (๑•̀ㅂ•́)و✧

**Comment by zd20041** [comment]
> 所有者

this branch -w is available

I won't use github

Do I have to do something?

Because I found that I still get the issue of -w error when downloading the latest version using pip

Including the pywebview[qt] version -w also has this problem
I'm sorry
Trouble for you

**Comment by zd20041** [comment]
When will this branch be released to pip?

**Comment by r0x0r** [comment]
@zd20041 now
