### ISSUE TITLE
not displaying any content in pyWebView[QT] in Linux

### ISSUE THREAD

**Issue by wehe64** [r0x0r/pywebview#1325]
### Specification
- pywebview version: 5.0.3[QT]
- operating system: 6.7.4-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Feb 10 09:41:20 UTC 2024 x86_64 GNU/Linux
- web renderer:
PyQt5==5.15.10
PyQt5-Qt5==5.15.2
PyQt5-sip==12.13.0
PyQtWebEngine==5.15.6
PyQtWebEngine-Qt5==5.15.2
pywebview==5.0.3
QtPy==2.4.1

### Description
-  just upgraded from 4.4.1 to 5.0.3 
-  doesn't display any contents at all
-  api alive, menus appear, logs look normal - window stays empty though
-  tried on two different boxes, even /w fresh venvs - always same result

### Practicalities
tried 
- examples/menu.html
- examples/change_url.html

FYI.... cheers / weHe

**Comment by r0x0r** [comment]
Does it work with simple_browser.py?

**Comment by wehe64** [comment]
yes, this worx - displays the external hello page fine.

**Comment by r0x0r** [comment]
This sounds like the QT blank screen problem addressed here lineshttps://github.com/r0x0r/pywebview/blob/38d69f2efc00c4077ff96f5a067bc4a6e5d3aa6f/webview/platforms/qt.py#L49 but Manjaro is already supported
Do you get any console messages? Especially if you set PYWEBVIEW_LOG=debug environment variable?

**Comment by wehe64** [comment]
indeed:
```
[pywebview] Using Qt 5.15.2
pywebview [DEBUG] Using Qt 5.15.2
[pywebview] Enable --no-sandbox flag for arch/manjaro/nixos
pywebview [DEBUG] Enable --no-sandbox flag for arch/manjaro/nixos

DevTools listening on ws://127.0.0.1:8228/devtools/browser/c7f18e4e-bc1e-42ad-8192-a615742a1611
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:8228
```
Strangely, I'm unable to get a debugging connection - I'm setting webview.start(..., debug=True, ...) but the WebDevConsole doesn't open, and neither can I connect remotely to the debugger from Brave or Chromium (which works normally).

**Comment by wehe64** [comment]
FYI, 
`Release of profile requested but WebEnginePage still not deleted. Expect troubles !`
5.0.4 on Linux, after I close the webview, just before the app exits

**Comment by r0x0r** [comment]
This one should now be fixed in master. 
Could you do `git bisect` on the master branch to check for the earliest bad commit? I do not have a Manjaro setup to reproduce this problem.

**Comment by wehe64** [comment]
```
250e2d546a765b85678a2e8cfa3b1ee3e82c24b3 is the first bad commit
commit 250e2d546a765b85678a2e8cfa3b1ee3e82c24b3
Author: Roman Sirokov <roman@flowrl.com>
Date:   Fri Sep 29 21:18:52 2023 +0300

    Implement APP_FLAGS

 examples/flags.py                 | 24 ++++++++++++++++++++++++
 examples/links.py                 |  2 --
 webview/__init__.py               |  5 +++++
 webview/platforms/cef.py          |  4 ++--
 webview/platforms/cocoa.py        | 10 +++++++---
 webview/platforms/edgechromium.py | 12 ++++++++----
 webview/platforms/gtk.py          | 15 +++++++++++----
 webview/platforms/qt.py           | 29 +++++++++++++++++------------
 8 files changed, 74 insertions(+), 27 deletions(-)
 create mode 100644 examples/flags.py

```

**Comment by r0x0r** [comment]
There is not much going on in this commit. Try following things 
- Add `environ_append("QTWEBENGINE_CHROMIUM_FLAGS", "--no-sandbox", "--no-sandbox")`` in the beginning of qt.py
- Set `self.nav_handler = None` in WebPage's init.

<img width="716" alt="image" src="https://github.com/r0x0r/pywebview/assets/1549657/e1f97dd7-80a0-461a-beed-d4e1991a79d2">

**Comment by wehe64** [comment]
these two did the job - 5.x[qt] blank screen gone.
(the 1st is essential, the 2nd made no difference)

**Comment by r0x0r** [comment]
Released in 5.0.5

**Comment by wehe64** [comment]
Thanx a lot!

**Comment by wehe64** [comment]
repo install 5.0.5 works ok confirmed

**Comment by Aran-Fey** [comment]
I'm confused. I got the message "[pywebview] Enable --no-sandbox flag for arch/manjaro/nixos" in the terminal and was trying to find out how to do that, but judging from this conversation it looks like pywebview already does this automatically? If that message isn't intended as an instruction for the user, then please rephrase it.

**Comment by wehe64** [comment]
As far as I remember(!!) from looking at the sources for qt 
I believe the flag is enabled hardcoded and is always active for qt.
