### ISSUE TITLE
OSX exception on file_dialog.py example.

### ISSUE THREAD

**Issue by paperscissors** [r0x0r/pywebview#14]
2015-11-01 13:59:28.703 Python[840:19718] This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes.  This will cause an exception in a future release.
 Stack:(
	0   CoreFoundation                      0x00007fff8ac1803c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8cb0676e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8ac17eed +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff832405c0 _AssertAutolayoutOnMainThreadOnly + 83
	4   Foundation                          0x00007fff83240412 -[NSISEngine withBehaviors:performModifications:] + 31
	5   AppKit                              0x00007fff8d8fcd20 -[NSWindow(NSConstraintBasedLayout) layoutIfNeeded] + 217
	6   AppKit                              0x00007fff8d8465cd -[NSWindow _setUpFirstResponderBeforeBecomingVisible] + 63
	7   AppKit                              0x00007fff8d9668a6 -[NSApplication _orderFrontModalWindow:relativeToWindow:] + 643
	8   AppKit                              0x00007fff8d966289 -[NSApplication _commonBeginModalSessionForWindow:relativeToWindow:modalDelegate:didEndSelector:contextInfo:] + 815
	9   AppKit                              0x00007fff8d965f47 -[NSApplication beginModalSessionForWindow:] + 37
	10  AppKit                              0x00007fff8d965e61 -[NSApplication runModalForWindow:] + 98
	11  AppKit                              0x00007fff8ddaca84 -[NSSavePanel runModal] + 323
	12  _objc.so                            0x000000010b5f37a7 ffi_call_unix64 + 79
	13  ???                                 0x0000000111491380 0x0 + 4584969088
)
2015-11-01 13:59:28.704 Python[840:19718] This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes.  This will cause an exception in a future release.
 Stack:(
	0   CoreFoundation                      0x00007fff8ac1803c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8cb0676e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8ac17eed +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff832405c0 _AssertAutolayoutOnMainThreadOnly + 83
	4   Foundation                          0x00007fff83246461 -[NSISEngine optimize] + 49
	5   AppKit                              0x00007fff8d8fcdf8 -[NSWindow(NSConstraintBasedLayout) _changeWindowFrameFromConstraintsIfNecessary] + 148
	6   Foundation                          0x00007fff8324048e -[NSISEngine withBehaviors:performModifications:] + 155
	7   AppKit                              0x00007fff8d8fcd20 -[NSWindow(NSConstraintBasedLayout) layoutIfNeeded] + 217
	8   AppKit                              0x00007fff8d8465cd -[NSWindow _setUpFirstResponderBeforeBecomingVisible] + 63
	9   AppKit                              0x00007fff8d9668a6 -[NSApplication _orderFrontModalWindow:relativeToWindow:] + 643
	10  AppKit                              0x00007fff8d966289 -[NSApplication _commonBeginModalSessionForWindow:relativeToWindow:modalDelegate:didEndSelector:contextInfo:] + 815
	11  AppKit                              0x00007fff8d965f47 -[NSApplication beginModalSessionForWindow:] + 37
	12  AppKit                              0x00007fff8d965e61 -[NSApplication runModalForWindow:] + 98
	13  AppKit                              0x00007fff8ddaca84 -[NSSavePanel runModal] + 323
	14  _objc.so                            0x000000010b5f37a7 ffi_call_unix64 + 79
	15  ???                                 0x0000000111491380 0x0 + 4584969088
)
2015-11-01 13:59:28.705 Python[840:19718] This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes.  This will cause an exception in a future release.
 Stack:(
	0   CoreFoundation                      0x00007fff8ac1803c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8cb0676e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8ac17eed +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff832405c0 _AssertAutolayoutOnMainThreadOnly + 83
	4   Foundation                          0x00007fff83240412 -[NSISEngine withBehaviors:performModifications:] + 31
	5   Foundation                          0x00007fff832475ba -[NSISEngine fixupIntegralizationViolations] + 104
	6   Foundation                          0x00007fff832464e0 -[NSISEngine optimize] + 176
	7   AppKit                              0x00007fff8d8fcdf8 -[NSWindow(NSConstraintBasedLayout) _changeWindowFrameFromConstraintsIfNecessary] + 148
	8   Foundation                          0x00007fff8324048e -[NSISEngine withBehaviors:performModifications:] + 155
	9   AppKit                              0x00007fff8d8fcd20 -[NSWindow(NSConstraintBasedLayout) layoutIfNeeded] + 217
	10  AppKit                              0x00007fff8d8465cd -[NSWindow _setUpFirstResponderBeforeBecomingVisible] + 63
	11  AppKit                              0x00007fff8d9668a6 -[NSApplication _orderFrontModalWindow:relativeToWindow:] + 643
	12  AppKit                              0x00007fff8d966289 -[NSApplication _commonBeginModalSessionForWindow:relativeToWindow:modalDelegate:didEndSelector:contextInfo:] + 815
	13  AppKit                              0x00007fff8d965f47 -[NSApplication beginModalSessionForWindow:] + 37
	14  AppKit                              0x00007fff8d965e61 -[NSApplication runModalForWindow:] + 98
	15  AppKit                              0x00007fff8ddaca84 -[NSSavePanel runModal] + 323
	16  _objc.so                            0x000000010b5f37a7 ffi_call_unix64 + 79
	17  ???                                 0x0000000111491380 0x0 + 4584969088
)

**Comment by r0x0r** [comment]
I have pushed a fix on master. Would you check if it eliminates the exception?
Thanks.

**Comment by paperscissors** [comment]
It still happens, it looks like.

It's happening on the attempt to open file dialog, line 11 of file_dialog.py.

```
print(webview.create_file_dialog(webview.OPEN_DIALOG, allow_multiple=True))
```

**Comment by paperscissors** [comment]
I guess I should mention, I'm on 10.10.5, running Python 2.7.

**Comment by r0x0r** [comment]
I cannot reproduce it on 10.10.5. I have changed it to create a dialog from the UI thread, which should eliminate the problem. Are you sure you test with the up-to-date master and not the version installed from pip?
