### ISSUE TITLE
Getting error: 'NoneType' object has no attribute 'frame'

### ISSUE THREAD

**Issue by lior-ps** [r0x0r/pywebview#1584]
The following code on Mac gets the error in the title:

import webview

def gui_loop_started():
    import AppKit 
    AppKit.NSApp.setActivationPolicy_(1) 

self._window = webview.create_window(
            "",
            draggable=True,
            frameless=True,
            hidden=True,
            js_api=self,
            on_top=True,
            resizable=False,
            transparent=sys.platform != "win32"
        )

webview.start(func=gui_loop_started)

**Comment by r0x0r** [comment]
Your code does not make sense. You have to create a window first

**Comment by lior-ps** [comment]
fixed the code example

**Comment by r0x0r** [comment]
Your code is not runnable nor standalone, so I still do not know what you are trying to achieve. But the code below  runs fine on my machine 


``` python
import webview

def gui_loop_started():
  import AppKit
  AppKit.NSApp.setActivationPolicy_(1)

_window = webview.create_window(
  "",
  html="<h1>Hello, World!</h1>",
  draggable=True,
  frameless=True,
  on_top=True,
  resizable=False,
)

webview.start(gui_loop_started)
```

**Comment by lior-ps** [comment]
it works for me as well
it happened only when loading it from a LaunchDaemon in mac after reboot

**Comment by ofir-ps** [comment]
For future reference, this problem occurs when calling `webview.start()` before screens are available in MacOS, resulting with the above failure in `self.screen = AppKit.NSScreen.mainScreen().frame()` while creating the BrowserView (cocoa.py)
