### ISSUE TITLE
set from master does not install .js or lib folders

### ISSUE THREAD

**Issue by jjgalvez** [r0x0r/pywebview#200]
### Specification
- Platform: Arch Linux
- Version: python3.6

### Description
installed from git and the js and lib folders do not get installed in the webview folder

**Comment by shivaprsdv** [comment]
Possible duplicate of #192. Please read r0x0r's reply to that issue.

**Comment by r0x0r** [comment]
I pushed an updated setup.py to master. lib is only copied on Windows.
Please test if it works for you

**Comment by jjgalvez** [comment]
just tried installing it again, still not working, the js folder is not copied to the webview package

**Comment by r0x0r** [comment]
It works on one machine, but not on another. There is something wrong with the configuration it seems. Anyhow I've got more pressing issues to deal with right now. I will get around to investigating at some point.
Please consider making a pull request, if you would like to get it fixed asap.

**Comment by jjgalvez** [comment]
no worries, I know you must be busy with the transition to 2.0.  I may take a look at it and see if can figure it out, it I do I'll let you know. Either way I'm sure you will have it all sorted out for 2.0.  BTW very cool package, I like using it with flask.

**Comment by adbenitez** [comment]
same problem here: `ImportError: No module named 'webview.js'`

**Comment by jjgalvez** [comment]
I've got a fix for the setup file that works with Linux, I was going to test it on my Mac. I don't have access to windows to test it on, but thought I would send it as a patch if it worked on my Mac later today. 


Jose




Get Outlook for Android







On Fri, Mar 23, 2018 at 12:08 AM -0400, "Asiel Díaz Benítez" <notifications@github.com> wrote:












same problem here: ImportError: No module named 'webview.js'

**Comment by r0x0r** [comment]
Fixed in master now
